<?php
/**
 * Core Action
 *
 * LICENSE
 *
 * This file is intellectual property of Core Action, LLC and may not
 * be used without permission.
 *
 * @category  HalfPipe
 * @copyright Copyright (c) 2010 Core Action. (http://coreaction.com/)
 */

use Core\Engine\View,
    Core\HalfPipe\Entity,
    Core\HalfPipe\View\Helper\Chip;

/* @var $this View */
?>
<p>
    We believe that this occurred because of reasons such as, but not limited to:
</p>

<ul>
    <li>An incorrect url was provided</li>
    <li>The page got misplaced by our monkey</li>
    <li>It got eaten by the dik-diks</li>
    <li>The server is mad at you</li>
</ul>