<?php
/**
 * Core Action
 *
 * LICENSE
 *
 * This file is intellectual property of Core Action, LLC and may not
 * be used without permission.
 *
 * @category  HalfPipe
 * @copyright Copyright (c) 2010 Core Action. (http://coreaction.com/)
 */

use Core\Engine\View,
    Core\HalfPipe\Entity,
    Core\HalfPipe\View\Helper\Chip;

/* @var $this View */
?>
<div>
    <h2>Sorry, but we don't exactly know who you are</h2>

    <p>
        The page requested required that you login to view it.
    </p>

    <h3>More Information</h3>

    <p>
        The 401 Unauthorized error is an HTTP status code that means the page
        you were trying to access can not be loaded until you first log on with
        a valid user ID and password. If you have just logged on and received the
        401 Unauthorized error, it means that the credentials you entered were invalid for some reason.
    </p>
</div>