<?php
/**
 * Core Action
 *
 * LICENSE
 *
 * This file is intellectual property of Core Action, LLC and may not
 * be used without permission.
 *
 * @category  HalfPipe
 * @copyright Copyright (c) 2010 Core Action. (http://coreaction.com/)
 */

use Core\Engine\View;

/* @var $this View */
?>
<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->
<? if ($this->pageCount > 1): ?>
<div class="pagination-container">
    <div class="pagination-control">
        <!-- Previous page link -->
        <? if (isset($this->previous)): ?>
            <a href="<?= $this->url(array('page' => $this->previous), $this->route) ?>">- Previous</a>
        <? else : ?>
            <span class="disabled">- Previous</span>
        <? endif; ?>

        <!-- Numbered page links -->
        <span class="page-indicator">(Page <?=@ $this->current ?> of <?=@ $this->pageCount ?>)</span>

        <!-- Next page link -->
        <? if (isset($this->next)): ?>
            <a href="<?= $this->url(array('page' => $this->next), $this->route) ?>">Next +</a>
        <? else : ?>
            <span class="disabled">Next +</span>
        <? endif ?>
    </div>
</div>
<? endif ?>